version: '3.6'

services:
    fastify:
        build: ./be
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./be
              target: /app
              consistency: native
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - ./data/database:/var/lib/mysql
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - default

networks:
    default:
