version: '3.6'

services:
    nginx:
        image: nginx:1.15.7-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/default.conf:/etc/nginx/default.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        networks:
            - default
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - default
    fastify:
        build: ./be
        ports:
            - "3000:3000"
        volumes:
            - ./be/logs:/app/logs
        # volumes:
        #     - type: bind
        #       source: ./be
        #       target: /app
        #       consistency: native
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - ./data/database:/var/lib/mysql
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - default

networks:
    default:
